version: '3.8'

services:
  minio: 
    image: minio/minio
    ports:
      - "9000:9000"     #API PORT
      - "9001:9001"     #CONSOLE PORT
    environment:
      MINIO_ROOT_USER: minioadmin                   #Your access key
      MINIO_ROOT_PASSWORD: minioadmin               #Your secret key
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  minio_data:
