baseURL = "https://www.kider.com"
languageCode = "en-us"
title = "Kider - Preschool Website"
theme = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Classes"
    url = "/classes/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[params]
  description = "Kider - Preschool Website Template"
  author = "HTML Codex"
  [params.contact]
    address = "123 Street, New York, USA"
    phone = "+012 345 67890"
    email = "info@example.com"
